### ISSUE TITLE
Crash during world load

### ISSUE THREAD

**Issue by Tyrius1** [PolarFox27/JobsMod#7]
https://pastebin.com/kDsqUx22
Forge 36.2.2
Minecraft 1.16.5
Jobs 2.0

**Comment by PolarFox27** [comment]
This issue does not come from the Jobs mod, as you can see in the error stacktrace, because all the errors are occuring in classes from this package : com.bottomtextdanny.dannys_expansion.core. Jobs is incompatible with this mod, but I cannot do anything about it. Ask the author of the dannys_expansion mod to update its code to make it compatible with other Player Capabilities.

I hope this message helped you, but I cannot fix this issue myself

**Comment by Tyrius1** [comment]
Jobs is also incompatible with curios api and occultism. Dropping Danny's Expansion and Occultism both are worth considering but dropping Curios means dropping the dozens of mods that rely on it. Just a heads up.

**Comment by PolarFox27** [comment]
Send me the crash report where you see that Jobs is incompatible with curios, I'll check if I can do something about it.

**Comment by Tyrius1** [comment]
https://pastebin.com/1FRaHKr1
